/*
 * This file is generated by jOOQ.
 */
package kata.jooq.tables.records;


import java.time.LocalDate;

import kata.jooq.tables.Users;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>users.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>users.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>users.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>users.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>users.dob</code>.
     */
    public void setDob(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>users.dob</code>.
     */
    public LocalDate getDob() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>users.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>users.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>users.phone</code>.
     */
    public void setPhone(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>users.phone</code>.
     */
    public String getPhone() {
        return (String) get(4);
    }

    /**
     * Setter for <code>users.is_active</code>.
     */
    public void setIsActive(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>users.is_active</code>.
     */
    public Integer getIsActive() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>users.location</code>.
     */
    public void setLocation(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>users.location</code>.
     */
    public String getLocation() {
        return (String) get(6);
    }

    /**
     * Setter for <code>users.preferences</code>.
     */
    public void setPreferences(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>users.preferences</code>.
     */
    public String getPreferences() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Integer id, String name, LocalDate dob, String email, String phone, Integer isActive, String location, String preferences) {
        super(Users.USERS);

        setId(id);
        setName(name);
        setDob(dob);
        setEmail(email);
        setPhone(phone);
        setIsActive(isActive);
        setLocation(location);
        setPreferences(preferences);
        resetChangedOnNotNull();
    }
}
